---
- name: Create pids directory
  file: path={{pids_dir}} state=directory recurse=yes owner=demo group=demo

- name: Generate run script
  template: src=demo.j2 dest=/etc/systemd/system/{{package_name}}.service mode=u+x owner=demo group=demo

- name: Reload systemd
  command: systemctl daemon-reload

- name: Start application
  command: systemctl restart demo
